name: Sync Fork

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: BookManagerOrganization/BookManagerAngularApp
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/BookManagerOrganization/BookManagerAngularApp.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
